package us_enrichment

type PrincipalResponse struct {
	SmartyKey      string              `json:"smarty_key"`
	DataSetName    string              `json:"data_set_name"`
	DataSubsetName string              `json:"data_subset_name"`
	MatchedAddress MatchedAddress      `json:"matched_address"`
	Attributes     PrincipalAttributes `json:"attributes"`
	Etag           string
}

type MatchedAddress struct {
	Street  string `json:"street"`
	City    string `json:"city"`
	State   string `json:"state"`
	ZIPCode string `json:"zipcode"`
}

type PrincipalAttributes struct {
	FirstFloorSqft                  string             `json:"1st_floor_sqft"`
	SecondFloorSqft                 string             `json:"2nd_floor_sqft"`
	Acres                           string             `json:"acres"`
	AirConditioner                  string             `json:"air_conditioner"`
	ArborPergola                    string             `json:"arbor_pergola"`
	AssessedImprovementPercent      string             `json:"assessed_improvement_percent"`
	AssessedImprovementValue        string             `json:"assessed_improvement_value"`
	AssessedLandValue               string             `json:"assessed_land_value"`
	AssessedValue                   string             `json:"assessed_value"`
	AssessorLastUpdate              string             `json:"assessor_last_update"`
	AssessorTaxrollUpdate           string             `json:"assessor_taxroll_update"`
	AtticArea                       string             `json:"attic_area"`
	AtticFlag                       string             `json:"attic_flag"`
	Balcony                         string             `json:"balcony"`
	BalconyArea                     string             `json:"balcony_area"`
	BasementSqft                    string             `json:"basement_sqft"`
	BasementSqftFinished            string             `json:"basement_sqft_finished"`
	BasementSqftUnfinished          string             `json:"basement_sqft_unfinished"`
	BathHouse                       string             `json:"bath_house"`
	BathHouseSqft                   string             `json:"bath_house_sqft"`
	BathroomsPartial                string             `json:"bathrooms_partial"`
	BathroomsTotal                  string             `json:"bathrooms_total"`
	Bedrooms                        string             `json:"bedrooms"`
	Block1                          string             `json:"block1"`
	Block2                          string             `json:"block2"`
	BoatAccess                      string             `json:"boat_access"`
	BoatHouse                       string             `json:"boat_house"`
	BoatHouseSqft                   string             `json:"boat_house_sqft"`
	BoatLift                        string             `json:"boat_lift"`
	BonusRoom                       string             `json:"bonus_room"`
	BreakfastNook                   string             `json:"breakfast_nook"`
	Breezeway                       string             `json:"breezeway"`
	BuildingDefinitionCode          string             `json:"building_definition_code"`
	BuildingSqft                    string             `json:"building_sqft"`
	Cabin                           string             `json:"cabin"`
	CabinSqft                       string             `json:"cabin_sqft"`
	Canopy                          string             `json:"canopy"`
	CanopySqft                      string             `json:"canopy_sqft"`
	Carport                         string             `json:"carport"`
	CarportSqft                     string             `json:"carport_sqft"`
	CbsaCode                        string             `json:"cbsa_code"`
	CbsaName                        string             `json:"cbsa_name"`
	Cellar                          string             `json:"cellar"`
	CensusBlock                     string             `json:"census_block"`
	CensusBlockGroup                string             `json:"census_block_group"`
	CensusFipsPlaceCode             string             `json:"census_fips_place_code"`
	CensusTract                     string             `json:"census_tract"`
	CentralVacuum                   string             `json:"central_vacuum"`
	CodeTitleCompany                string             `json:"code_title_company"`
	CombinedStatisticalArea         string             `json:"combined_statistical_area"`
	CommunityRec                    string             `json:"community_rec"`
	CompanyFlag                     string             `json:"company_flag"`
	CongressionalDistrict           string             `json:"congressional_district"`
	ConstructionType                string             `json:"construction_type"`
	ContactCity                     string             `json:"contact_city"`
	ContactCrrt                     string             `json:"contact_crrt"`
	ContactFullAddress              string             `json:"contact_full_address"`
	ContactHouseNumber              string             `json:"contact_house_number"`
	ContactMailInfoFormat           string             `json:"contact_mail_info_format"`
	ContactMailInfoPrivacy          string             `json:"contact_mail_info_privacy"`
	ContactMailingCounty            string             `json:"contact_mailing_county"`
	ContactMailingFips              string             `json:"contact_mailing_fips"`
	ContactPostDirection            string             `json:"contact_post_direction"`
	ContactPreDirection             string             `json:"contact_pre_direction"`
	ContactState                    string             `json:"contact_state"`
	ContactStreetName               string             `json:"contact_street_name"`
	ContactSuffix                   string             `json:"contact_suffix"`
	ContactUnitDesignator           string             `json:"contact_unit_designator"`
	ContactValue                    string             `json:"contact_value"`
	ContactZip                      string             `json:"contact_zip"`
	ContactZip4                     string             `json:"contact_zip4"`
	Courtyard                       string             `json:"courtyard"`
	CourtyardArea                   string             `json:"courtyard_area"`
	Deck                            string             `json:"deck"`
	DeckArea                        string             `json:"deck_area"`
	DeedDocumentPage                string             `json:"deed_document_page"`
	DeedDocumentBook                string             `json:"deed_document_book"`
	DeedDocumentNumber              string             `json:"deed_document_number"`
	DeedOwnerFirstName              string             `json:"deed_owner_first_name"`
	DeedOwnerFirstName2             string             `json:"deed_owner_first_name2"`
	DeedOwnerFirstName3             string             `json:"deed_owner_first_name3"`
	DeedOwnerFirstName4             string             `json:"deed_owner_first_name4"`
	DeedOwnerFullName               string             `json:"deed_owner_full_name"`
	DeedOwnerFullName2              string             `json:"deed_owner_full_name2"`
	DeedOwnerFullName3              string             `json:"deed_owner_full_name3"`
	DeedOwnerFullName4              string             `json:"deed_owner_full_name4"`
	DeedOwnerLastName               string             `json:"deed_owner_last_name"`
	DeedOwnerLastName2              string             `json:"deed_owner_last_name2"`
	DeedOwnerLastName3              string             `json:"deed_owner_last_name3"`
	DeedOwnerLastName4              string             `json:"deed_owner_last_name4"`
	DeedOwnerMiddleName             string             `json:"deed_owner_middle_name"`
	DeedOwnerMiddleName2            string             `json:"deed_owner_middle_name2"`
	DeedOwnerMiddleName3            string             `json:"deed_owner_middle_name3"`
	DeedOwnerMiddleName4            string             `json:"deed_owner_middle_name4"`
	DeedOwnerSuffix                 string             `json:"deed_owner_suffix"`
	DeedOwnerSuffix2                string             `json:"deed_owner_suffix2"`
	DeedOwnerSuffix3                string             `json:"deed_owner_suffix3"`
	DeedOwnerSuffix4                string             `json:"deed_owner_suffix4"`
	DeedSaleDate                    string             `json:"deed_sale_date"`
	DeedSalePrice                   string             `json:"deed_sale_price"`
	DeedTransactionId               string             `json:"deed_transaction_id"`
	DepthLinearFootage              string             `json:"depth_linear_footage"`
	DisabledTaxExemption            string             `json:"disabled_tax_exemption"`
	DocumentTypeDescription         string             `json:"document_type_description"`
	DrivewaySqft                    string             `json:"driveway_sqft"`
	DrivewayType                    string             `json:"driveway_type"`
	EffectiveYearBuilt              string             `json:"effective_year_built"`
	ElevationFeet                   string             `json:"elevation_feet"`
	Elevator                        string             `json:"elevator"`
	EquestrianArena                 string             `json:"equestrian_arena"`
	Escalator                       string             `json:"escalator"`
	ExerciseRoom                    string             `json:"exercise_room"`
	ExteriorWalls                   string             `json:"exterior_walls"`
	FamilyRoom                      string             `json:"family_room"`
	Fence                           string             `json:"fence"`
	FenceArea                       string             `json:"fence_area"`
	FinancialHistory                []FinancialHistory `json:"financial_history"`
	FipsCode                        string             `json:"fips_code"`
	FireResistanceCode              string             `json:"fire_resistance_code"`
	FireSprinklersFlag              string             `json:"fire_sprinklers_flag"`
	Fireplace                       string             `json:"fireplace"`
	FireplaceNumber                 string             `json:"fireplace_number"`
	FirstName                       string             `json:"first_name"`
	FirstName2                      string             `json:"first_name_2"`
	FirstName3                      string             `json:"first_name_3"`
	FirstName4                      string             `json:"first_name_4"`
	Flooring                        string             `json:"flooring"`
	Foundation                      string             `json:"foundation"`
	GameRoom                        string             `json:"game_room"`
	Garage                          string             `json:"garage"`
	GarageSqft                      string             `json:"garage_sqft"`
	Gazebo                          string             `json:"gazebo"`
	GazeboSqft                      string             `json:"gazebo_sqft"`
	GolfCourse                      string             `json:"golf_course"`
	Grainery                        string             `json:"grainery"`
	GrainerySqft                    string             `json:"grainery_sqft"`
	GreatRoom                       string             `json:"great_room"`
	Greenhouse                      string             `json:"greenhouse"`
	GreenhouseSqft                  string             `json:"greenhouse_sqft"`
	GrossSqft                       string             `json:"gross_sqft"`
	Guesthouse                      string             `json:"guesthouse"`
	GuesthouseSqft                  string             `json:"guesthouse_sqft"`
	HandicapAccessibility           string             `json:"handicap_accessibility"`
	Heat                            string             `json:"heat"`
	HeatFuelType                    string             `json:"heat_fuel_type"`
	HobbyRoom                       string             `json:"hobby_room"`
	HomeownerTaxExemption           string             `json:"homeowner_tax_exemption"`
	InstrumentDate                  string             `json:"instrument_date"`
	IntercomSystem                  string             `json:"intercom_system"`
	InterestRateType2               string             `json:"interest_rate_type_2"`
	InteriorStructure               string             `json:"interior_structure"`
	Kennel                          string             `json:"kennel"`
	KennelSqft                      string             `json:"kennel_sqft"`
	LandUseCode                     string             `json:"land_use_code"`
	LandUseGroup                    string             `json:"land_use_group"`
	LandUseStandard                 string             `json:"land_use_standard"`
	LastName                        string             `json:"last_name"`
	LastName2                       string             `json:"last_name_2"`
	LastName3                       string             `json:"last_name_3"`
	LastName4                       string             `json:"last_name_4"`
	Latitude                        string             `json:"latitude"`
	Laundry                         string             `json:"laundry"`
	LeanTo                          string             `json:"lean_to"`
	LeanToSqft                      string             `json:"lean_to_sqft"`
	LegalDescription                string             `json:"legal_description"`
	LegalUnit                       string             `json:"legal_unit"`
	LenderAddress                   string             `json:"lender_address"`
	LenderAddress2                  string             `json:"lender_address_2"`
	LenderCity                      string             `json:"lender_city"`
	LenderCity2                     string             `json:"lender_city_2"`
	LenderCode2                     string             `json:"lender_code_2"`
	LenderFirstName                 string             `json:"lender_first_name"`
	LenderFirstName2                string             `json:"lender_first_name_2"`
	LenderLastName                  string             `json:"lender_last_name"`
	LenderLastName2                 string             `json:"lender_last_name_2"`
	LenderName                      string             `json:"lender_name"`
	LenderName2                     string             `json:"lender_name_2"`
	LenderSellerCarryBack           string             `json:"lender_seller_carry_back"`
	LenderSellerCarryBack2          string             `json:"lender_seller_carry_back_2"`
	LenderState                     string             `json:"lender_state"`
	LenderState2                    string             `json:"lender_state_2"`
	LenderZip                       string             `json:"lender_zip"`
	LenderZip2                      string             `json:"lender_zip_2"`
	LenderZipExtended               string             `json:"lender_zip_extended"`
	LenderZipExtended2              string             `json:"lender_zip_extended_2"`
	LoadingPlatform                 string             `json:"loading_platform"`
	LoadingPlatformSqft             string             `json:"loading_platform_sqft"`
	Longitude                       string             `json:"longitude"`
	Lot1                            string             `json:"lot_1"`
	Lot2                            string             `json:"lot_2"`
	Lot3                            string             `json:"lot_3"`
	LotSqft                         string             `json:"lot_sqft"`
	MarketImprovementPercent        string             `json:"market_improvement_percent"`
	MarketImprovementValue          string             `json:"market_improvement_value"`
	MarketLandValue                 string             `json:"market_land_value"`
	MarketValueYear                 string             `json:"market_value_year"`
	MatchType                       string             `json:"match_type"`
	MediaRoom                       string             `json:"media_room"`
	MetroDivision                   string             `json:"metro_division"`
	MiddleName                      string             `json:"middle_name"`
	MiddleName2                     string             `json:"middle_name_2"`
	MiddleName3                     string             `json:"middle_name_3"`
	MiddleName4                     string             `json:"middle_name_4"`
	Milkhouse                       string             `json:"milkhouse"`
	MilkhouseSqft                   string             `json:"milkhouse_sqft"`
	MinorCivilDivisionCode          string             `json:"minor_civil_division_code"`
	MinorCivilDivisionName          string             `json:"minor_civil_division_name"`
	MobileHomeHookup                string             `json:"mobile_home_hookup"`
	MortgageAmount                  string             `json:"mortgage_amount"`
	MortgageAmount2                 string             `json:"mortgage_amount_2"`
	MortgageDueDate                 string             `json:"mortgage_due_date"`
	MortgageDueDate2                string             `json:"mortgage_due_date_2"`
	MortgageInterestRate            string             `json:"mortgage_interest_rate"`
	MortgageInterestRateType        string             `json:"mortgage_interest_rate_type"`
	MortgageLenderCode              string             `json:"mortgage_lender_code"`
	MortgageRate2                   string             `json:"mortgage_rate_2"`
	MortgageRecordingDate           string             `json:"mortgage_recording_date"`
	MortgageRecordingDate2          string             `json:"mortgage_recording_date_2"`
	MortgageTerm                    string             `json:"mortgage_term"`
	MortgageTerm2                   string             `json:"mortgage_term_2"`
	MortgageTermType                string             `json:"mortgage_term_type"`
	MortgageTermType2               string             `json:"mortgage_term_type_2"`
	MortgageType                    string             `json:"mortgage_type"`
	MortgageType2                   string             `json:"mortgage_type_2"`
	MsaCode                         string             `json:"msa_code"`
	MsaName                         string             `json:"msa_name"`
	MudRoom                         string             `json:"mud_room"`
	MultiParcelFlag                 string             `json:"multi_parcel_flag"`
	NameTitleCompany                string             `json:"name_title_company"`
	NeighborhoodCode                string             `json:"neighborhood_code"`
	NumberOfBuildings               string             `json:"number_of_buildings"`
	Office                          string             `json:"office"`
	OfficeSqft                      string             `json:"office_sqft"`
	OtherTaxExemption               string             `json:"other_tax_exemption"`
	OutdoorKitchenFireplace         string             `json:"outdoor_kitchen_fireplace"`
	OverheadDoor                    string             `json:"overhead_door"`
	OwnerFullName                   string             `json:"owner_full_name"`
	OwnerFullName2                  string             `json:"owner_full_name_2"`
	OwnerFullName3                  string             `json:"owner_full_name_3"`
	OwnerFullName4                  string             `json:"owner_full_name_4"`
	OwnerOccupancyStatus            string             `json:"owner_occupancy_status"`
	OwnershipTransferDate           string             `json:"ownership_transfer_date"`
	OwnershipTransferDocNumber      string             `json:"ownership_transfer_doc_number"`
	OwnershipTransferTransactionId  string             `json:"ownership_transfer_transaction_id"`
	OwnershipType                   string             `json:"ownership_type"`
	OwnershipType2                  string             `json:"ownership_type_2"`
	OwnershipVestingRelationCode    string             `json:"ownership_vesting_relation_code"`
	ParcelAccountNumber             string             `json:"parcel_account_number"`
	ParcelMapBook                   string             `json:"parcel_map_book"`
	ParcelMapPage                   string             `json:"parcel_map_page"`
	ParcelNumberAlternate           string             `json:"parcel_number_alternate"`
	ParcelNumberFormatted           string             `json:"parcel_number_formatted"`
	ParcelNumberPrevious            string             `json:"parcel_number_previous"`
	ParcelNumberYearAdded           string             `json:"parcel_number_year_added"`
	ParcelNumberYearChange          string             `json:"parcel_number_year_change"`
	ParcelRawNumber                 string             `json:"parcel_raw_number"`
	ParcelShellRecord               string             `json:"parcel_shell_record"`
	ParkingSpaces                   string             `json:"parking_spaces"`
	PatioArea                       string             `json:"patio_area"`
	PhaseName                       string             `json:"phase_name"`
	PlumbingFixturesCount           string             `json:"plumbing_fixtures_count"`
	PoleStruct                      string             `json:"pole_struct"`
	PoleStructSqft                  string             `json:"pole_struct_sqft"`
	Pond                            string             `json:"pond"`
	Pool                            string             `json:"pool"`
	PoolArea                        string             `json:"pool_area"`
	Poolhouse                       string             `json:"poolhouse"`
	PoolhouseSqft                   string             `json:"poolhouse_sqft"`
	Porch                           string             `json:"porch"`
	PorchArea                       string             `json:"porch_area"`
	PoultryHouse                    string             `json:"poultry_house"`
	PoultryHouseSqft                string             `json:"poultry_house_sqft"`
	PreviousAssessedValue           string             `json:"previous_assessed_value"`
	PriorSaleAmount                 string             `json:"prior_sale_amount"`
	PriorSaleDate                   string             `json:"prior_sale_date"`
	PropertyAddressCarrierRouteCode string             `json:"property_address_carrier_route_code"`
	PropertyAddressCity             string             `json:"property_address_city"`
	PropertyAddressFull             string             `json:"property_address_full"`
	PropertyAddressHouseNumber      string             `json:"property_address_house_number"`
	PropertyAddressPostDirection    string             `json:"property_address_post_direction"`
	PropertyAddressPreDirection     string             `json:"property_address_pre_direction"`
	PropertyAddressState            string             `json:"property_address_state"`
	PropertyAddressStreetName       string             `json:"property_address_street_name"`
	PropertyAddressStreetSuffix     string             `json:"property_address_street_suffix"`
	PropertyAddressUnitDesignator   string             `json:"property_address_unit_designator"`
	PropertyAddressUnitValue        string             `json:"property_address_unit_value"`
	PropertyAddressZip4             string             `json:"property_address_zip_4"`
	PropertyAddressZipcode          string             `json:"property_address_zipcode"`
	PublicationDate                 string             `json:"publication_date"`
	Quarter                         string             `json:"quarter"`
	QuarterQuarter                  string             `json:"quarter_quarter"`
	Quonset                         string             `json:"quonset"`
	QuonsetSqft                     string             `json:"quonset_sqft"`
	Range                           string             `json:"range"`
	RecordingDate                   string             `json:"recording_date"`
	RoofCover                       string             `json:"roof_cover"`
	RoofFrame                       string             `json:"roof_frame"`
	Rooms                           string             `json:"rooms"`
	RvParking                       string             `json:"rv_parking"`
	SafeRoom                        string             `json:"safe_room"`
	SaleAmount                      string             `json:"sale_amount"`
	SaleDate                        string             `json:"sale_date"`
	Sauna                           string             `json:"sauna"`
	Section                         string             `json:"section"`
	SecurityAlarm                   string             `json:"security_alarm"`
	SeniorTaxExemption              string             `json:"senior_tax_exemption"`
	SewerType                       string             `json:"sewer_type"`
	Shed                            string             `json:"shed"`
	ShedSqft                        string             `json:"shed_sqft"`
	Silo                            string             `json:"silo"`
	SiloSqft                        string             `json:"silo_sqft"`
	SittingRoom                     string             `json:"sitting_room"`
	SitusCounty                     string             `json:"situs_county"`
	SitusState                      string             `json:"situs_state"`
	SoundSystem                     string             `json:"sound_system"`
	SportsCourt                     string             `json:"sports_court"`
	Sprinklers                      string             `json:"sprinklers"`
	Stable                          string             `json:"stable"`
	StableSqft                      string             `json:"stable_sqft"`
	StorageBuilding                 string             `json:"storage_building"`
	StorageBuildingSqft             string             `json:"storage_building_sqft"`
	StoriesNumber                   string             `json:"stories_number"`
	StormShelter                    string             `json:"storm_shelter"`
	StormShutter                    string             `json:"storm_shutter"`
	StructureStyle                  string             `json:"structure_style"`
	Study                           string             `json:"study"`
	Subdivision                     string             `json:"subdivision"`
	Suffix                          string             `json:"suffix"`
	Suffix2                         string             `json:"suffix_2"`
	Suffix3                         string             `json:"suffix_3"`
	Suffix4                         string             `json:"suffix_4"`
	Sunroom                         string             `json:"sunroom"`
	TaxAssessYear                   string             `json:"tax_assess_year"`
	TaxBilledAmount                 string             `json:"tax_billed_amount"`
	TaxDelinquentYear               string             `json:"tax_delinquent_year"`
	TaxFiscalYear                   string             `json:"tax_fiscal_year"`
	TaxJurisdiction                 string             `json:"tax_jurisdiction"`
	TaxRateArea                     string             `json:"tax_rate_area"`
	TennisCourt                     string             `json:"tennis_court"`
	TopographyCode                  string             `json:"topography_code"`
	TotalMarketValue                string             `json:"total_market_value"`
	Township                        string             `json:"township"`
	TractNumber                     string             `json:"tract_number"`
	TransferAmount                  string             `json:"transfer_amount"`
	TrustDescription                string             `json:"trust_description"`
	UnitCount                       string             `json:"unit_count"`
	UpperFloorsSqft                 string             `json:"upper_floors_sqft"`
	Utility                         string             `json:"utility"`
	UtilityBuilding                 string             `json:"utility_building"`
	UtilityBuildingSqft             string             `json:"utility_building_sqft"`
	UtilitySqft                     string             `json:"utility_sqft"`
	VeteranTaxExemption             string             `json:"veteran_tax_exemption"`
	ViewDescription                 string             `json:"view_description"`
	WaterFeature                    string             `json:"water_feature"`
	WaterServiceType                string             `json:"water_service_type"`
	WetBar                          string             `json:"wet_bar"`
	WidowTaxExemption               string             `json:"widow_tax_exemption"`
	WidthLinearFootage              string             `json:"width_linear_footage"`
	WineCellar                      string             `json:"wine_cellar"`
	YearBuilt                       string             `json:"year_built"`
	Zoning                          string             `json:"zoning"`
}

type FinancialHistory struct {
	CodeTitleCompany         string `json:"code_title_company"`
	DocumentTypeDescription  string `json:"document_type_description"`
	InstrumentDate           string `json:"instrument_date"`
	InterestRateType2        string `json:"interest_rate_type_2"`
	LenderAddress            string `json:"lender_address"`
	LenderAddress2           string `json:"lender_address_2"`
	LenderCity               string `json:"lender_city"`
	LenderCity2              string `json:"lender_city_2"`
	LenderCode2              string `json:"lender_code_2"`
	LenderFirstName          string `json:"lender_first_name"`
	LenderFirstName2         string `json:"lender_first_name_2"`
	LenderLastName           string `json:"lender_last_name"`
	LenderLastName2          string `json:"lender_last_name_2"`
	LenderName               string `json:"lender_name"`
	LenderName2              string `json:"lender_name_2"`
	LenderSellerCarryBack    string `json:"lender_seller_carry_back"`
	LenderSellerCarryBack2   string `json:"lender_seller_carry_back_2"`
	LenderState              string `json:"lender_state"`
	LenderState2             string `json:"lender_state_2"`
	LenderZip                string `json:"lender_zip"`
	LenderZip2               string `json:"lender_zip_2"`
	LenderZipExtended        string `json:"lender_zip_extended"`
	LenderZipExtended2       string `json:"lender_zip_extended_2"`
	MortgageAmount           string `json:"mortgage_amount"`
	MortgageAmount2          string `json:"mortgage_amount_2"`
	MortgageDueDate          string `json:"mortgage_due_date"`
	MortgageDueDate2         string `json:"mortgage_due_date_2"`
	MortgageInterestRate     string `json:"mortgage_interest_rate"`
	MortgageInterestRateType string `json:"mortgage_interest_rate_type"`
	MortgageLenderCode       string `json:"mortgage_lender_code"`
	MortgageRate2            string `json:"mortgage_rate_2"`
	MortgageRecordingDate    string `json:"mortgage_recording_date"`
	MortgageRecordingDate2   string `json:"mortgage_recording_date_2"`
	MortgageTerm             string `json:"mortgage_term"`
	MortgageTerm2            string `json:"mortgage_term_2"`
	MortgageTermType         string `json:"mortgage_term_type"`
	MortgageTermType2        string `json:"mortgage_term_type_2"`
	MortgageType             string `json:"mortgage_type"`
	MortgageType2            string `json:"mortgage_type_2"`
	MultiParcelFlag          string `json:"multi_parcel_flag"`
	NameTitleCompany         string `json:"name_title_company"`
	RecordingDate            string `json:"recording_date"`
	TransferAmount           string `json:"transfer_amount"`
}
type GeoReferenceResponse struct {
	SmartyKey      string                 `json:"smarty_key"`
	DataSetName    string                 `json:"data_set_name"`
	DataSetVersion string                 `json:"data_set_version"`
	MatchedAddress MatchedAddress         `json:"matched_address"`
	Attributes     GeoReferenceAttributes `json:"attributes"`
	Etag           string
}

type GeoReferenceAttributes struct {
	CensusBlock struct {
		Accuracy string `json:"accuracy"`
		GeoId    string `json:"geoid"`
	} `json:"census_block"`

	CensusCountyDivision struct {
		Accuracy string `json:"accuracy"`
		Code     string `json:"code"`
		Name     string `json:"name"`
	} `json:"census_county_division"`

	CensusTract struct {
		Code string `json:"code"`
	} `json:"census_tract"`

	CoreBasedStatArea struct {
		Code string `json:"code"`
		Name string `json:"name"`
	} `json:"core_based_stat_area"`

	Place struct {
		Accuracy string `json:"accuracy"`
		Code     string `json:"code"`
		Name     string `json:"name"`
		Type     string `json:"type"`
	} `json:"place"`
}

type RootAddress struct {
	SecondaryCount      uint64 `json:"secondary_count"`
	SmartyKey           string `json:"smarty_key"`
	PrimaryNumber       string `json:"primary_number"`
	StreetPredirection  string `json:"street_predirection"`
	StreetName          string `json:"street_name"`
	StreetSuffix        string `json:"street_suffix"`
	StreetPostdirection string `json:"street_postdirection"`
	CityName            string `json:"city_name"`
	StateAbbreviation   string `json:"state_abbreviation"`
	Zipcode             string `json:"zipcode"`
	Plus4Code           string `json:"plus4_code"`
}

type Alias struct {
	SmartyKey           string `json:"smarty_key"`
	PrimaryNumber       string `json:"primary_number"`
	StreetPredirection  string `json:"street_predirection"`
	StreetName          string `json:"street_name"`
	StreetSuffix        string `json:"street_suffix"`
	StreetPostdirection string `json:"street_postdirection"`
	CityName            string `json:"city_name"`
	StateAbbreviation   string `json:"state_abbreviation"`
	Zipcode             string `json:"zipcode"`
	Plus4Code           string `json:"plus4_code"`
}

type Secondary struct {
	SmartyKey           string         `json:"smarty_key"`
	MatchedAddress      MatchedAddress `json:"matched_address"`
	SecondaryDesignator string         `json:"secondary_designator"`
	SecondaryNumber     string         `json:"secondary_number"`
	Plus4Code           string         `json:"plus4_code"`
}

type SecondaryResponse struct {
	SmartyKey   string `json:"smarty_key"`
	Etag        string
	RootAddress RootAddress `json:"root_address"`
	Aliases     []Alias     `json:"aliases"`
	Secondaries []Secondary `json:"secondaries"`
}

type SecondaryCountResponse struct {
	SmartyKey string `json:"smarty_key"`
	Count     int    `json:"count"`
	Etag      string
}

type RiskResponse struct {
	SmartyKey      string         `json:"smarty_key"`
	DataSetName    string         `json:"data_set_name"`
	MatchedAddress MatchedAddress `json:"matched_address"`
	Attributes     RiskAttributes `json:"attributes"`
	Etag           string
}

type RiskAttributes struct {
	AGRIVALUE      string `json:"AGRIVALUE"`
	ALR_NPCTL      string `json:"ALR_NPCTL"`
	ALR_VALA       string `json:"ALR_VALA"`
	ALR_VALB       string `json:"ALR_VALB"`
	ALR_VALP       string `json:"ALR_VALP"`
	ALR_VRA_NPCTL  string `json:"ALR_VRA_NPCTL"`
	AREA           string `json:"AREA"`
	AVLN_AFREQ     string `json:"AVLN_AFREQ"`
	AVLN_ALRB      string `json:"AVLN_ALRB"`
	AVLN_ALRP      string `json:"AVLN_ALRP"`
	AVLN_ALR_NPCTL string `json:"AVLN_ALR_NPCTL"`
	AVLN_EALB      string `json:"AVLN_EALB"`
	AVLN_EALP      string `json:"AVLN_EALP"`
	AVLN_EALPE     string `json:"AVLN_EALPE"`
	AVLN_EALR      string `json:"AVLN_EALR"`
	AVLN_EALS      string `json:"AVLN_EALS"`
	AVLN_EALT      string `json:"AVLN_EALT"`
	AVLN_EVNTS     string `json:"AVLN_EVNTS"`
	AVLN_EXPB      string `json:"AVLN_EXPB"`
	AVLN_EXPP      string `json:"AVLN_EXPP"`
	AVLN_EXPPE     string `json:"AVLN_EXPPE"`
	AVLN_EXPT      string `json:"AVLN_EXPT"`
	AVLN_EXP_AREA  string `json:"AVLN_EXP_AREA"`
	AVLN_HLRB      string `json:"AVLN_HLRB"`
	AVLN_HLRP      string `json:"AVLN_HLRP"`
	AVLN_HLRR      string `json:"AVLN_HLRR"`
	AVLN_RISKR     string `json:"AVLN_RISKR"`
	AVLN_RISKS     string `json:"AVLN_RISKS"`
	AVLN_RISKV     string `json:"AVLN_RISKV"`
	BUILDVALUE     string `json:"BUILDVALUE"`
	CFLD_AFREQ     string `json:"CFLD_AFREQ"`
	CFLD_ALRB      string `json:"CFLD_ALRB"`
	CFLD_ALRP      string `json:"CFLD_ALRP"`
	CFLD_ALR_NPCTL string `json:"CFLD_ALR_NPCTL"`
	CFLD_EALB      string `json:"CFLD_EALB"`
	CFLD_EALP      string `json:"CFLD_EALP"`
	CFLD_EALPE     string `json:"CFLD_EALPE"`
	CFLD_EALR      string `json:"CFLD_EALR"`
	CFLD_EALS      string `json:"CFLD_EALS"`
	CFLD_EALT      string `json:"CFLD_EALT"`
	CFLD_EVNTS     string `json:"CFLD_EVNTS"`
	CFLD_EXPB      string `json:"CFLD_EXPB"`
	CFLD_EXPP      string `json:"CFLD_EXPP"`
	CFLD_EXPPE     string `json:"CFLD_EXPPE"`
	CFLD_EXPT      string `json:"CFLD_EXPT"`
	CFLD_EXP_AREA  string `json:"CFLD_EXP_AREA"`
	CFLD_HLRB      string `json:"CFLD_HLRB"`
	CFLD_HLRP      string `json:"CFLD_HLRP"`
	CFLD_HLRR      string `json:"CFLD_HLRR"`
	CFLD_RISKR     string `json:"CFLD_RISKR"`
	CFLD_RISKS     string `json:"CFLD_RISKS"`
	CFLD_RISKV     string `json:"CFLD_RISKV"`
	COUNTY         string `json:"COUNTY"`
	COUNTYFIPS     string `json:"COUNTYFIPS"`
	COUNTYTYPE     string `json:"COUNTYTYPE"`
	CRF_VALUE      string `json:"CRF_VALUE"`
	CWAV_AFREQ     string `json:"CWAV_AFREQ"`
	CWAV_ALRA      string `json:"CWAV_ALRA"`
	CWAV_ALRB      string `json:"CWAV_ALRB"`
	CWAV_ALRP      string `json:"CWAV_ALRP"`
	CWAV_ALR_NPCTL string `json:"CWAV_ALR_NPCTL"`
	CWAV_EALA      string `json:"CWAV_EALA"`
	CWAV_EALB      string `json:"CWAV_EALB"`
	CWAV_EALP      string `json:"CWAV_EALP"`
	CWAV_EALPE     string `json:"CWAV_EALPE"`
	CWAV_EALR      string `json:"CWAV_EALR"`
	CWAV_EALS      string `json:"CWAV_EALS"`
	CWAV_EALT      string `json:"CWAV_EALT"`
	CWAV_EVNTS     string `json:"CWAV_EVNTS"`
	CWAV_EXPA      string `json:"CWAV_EXPA"`
	CWAV_EXPB      string `json:"CWAV_EXPB"`
	CWAV_EXPP      string `json:"CWAV_EXPP"`
	CWAV_EXPPE     string `json:"CWAV_EXPPE"`
	CWAV_EXPT      string `json:"CWAV_EXPT"`
	CWAV_EXP_AREA  string `json:"CWAV_EXP_AREA"`
	CWAV_HLRA      string `json:"CWAV_HLRA"`
	CWAV_HLRB      string `json:"CWAV_HLRB"`
	CWAV_HLRP      string `json:"CWAV_HLRP"`
	CWAV_HLRR      string `json:"CWAV_HLRR"`
	CWAV_RISKR     string `json:"CWAV_RISKR"`
	CWAV_RISKS     string `json:"CWAV_RISKS"`
	CWAV_RISKV     string `json:"CWAV_RISKV"`
	DRGT_AFREQ     string `json:"DRGT_AFREQ"`
	DRGT_ALRA      string `json:"DRGT_ALRA"`
	DRGT_ALR_NPCTL string `json:"DRGT_ALR_NPCTL"`
	DRGT_EALA      string `json:"DRGT_EALA"`
	DRGT_EALR      string `json:"DRGT_EALR"`
	DRGT_EALS      string `json:"DRGT_EALS"`
	DRGT_EALT      string `json:"DRGT_EALT"`
	DRGT_EVNTS     string `json:"DRGT_EVNTS"`
	DRGT_EXPA      string `json:"DRGT_EXPA"`
	DRGT_EXPT      string `json:"DRGT_EXPT"`
	DRGT_EXP_AREA  string `json:"DRGT_EXP_AREA"`
	DRGT_HLRA      string `json:"DRGT_HLRA"`
	DRGT_HLRR      string `json:"DRGT_HLRR"`
	DRGT_RISKR     string `json:"DRGT_RISKR"`
	DRGT_RISKS     string `json:"DRGT_RISKS"`
	DRGT_RISKV     string `json:"DRGT_RISKV"`
	EAL_RATNG      string `json:"EAL_RATNG"`
	EAL_SCORE      string `json:"EAL_SCORE"`
	EAL_SPCTL      string `json:"EAL_SPCTL"`
	EAL_VALA       string `json:"EAL_VALA"`
	EAL_VALB       string `json:"EAL_VALB"`
	EAL_VALP       string `json:"EAL_VALP"`
	EAL_VALPE      string `json:"EAL_VALPE"`
	EAL_VALT       string `json:"EAL_VALT"`
	ERQK_AFREQ     string `json:"ERQK_AFREQ"`
	ERQK_ALRB      string `json:"ERQK_ALRB"`
	ERQK_ALRP      string `json:"ERQK_ALRP"`
	ERQK_ALR_NPCTL string `json:"ERQK_ALR_NPCTL"`
	ERQK_EALB      string `json:"ERQK_EALB"`
	ERQK_EALP      string `json:"ERQK_EALP"`
	ERQK_EALPE     string `json:"ERQK_EALPE"`
	ERQK_EALR      string `json:"ERQK_EALR"`
	ERQK_EALS      string `json:"ERQK_EALS"`
	ERQK_EALT      string `json:"ERQK_EALT"`
	ERQK_EVNTS     string `json:"ERQK_EVNTS"`
	ERQK_EXPB      string `json:"ERQK_EXPB"`
	ERQK_EXPP      string `json:"ERQK_EXPP"`
	ERQK_EXPPE     string `json:"ERQK_EXPPE"`
	ERQK_EXPT      string `json:"ERQK_EXPT"`
	ERQK_EXP_AREA  string `json:"ERQK_EXP_AREA"`
	ERQK_HLRB      string `json:"ERQK_HLRB"`
	ERQK_HLRP      string `json:"ERQK_HLRP"`
	ERQK_HLRR      string `json:"ERQK_HLRR"`
	ERQK_RISKR     string `json:"ERQK_RISKR"`
	ERQK_RISKS     string `json:"ERQK_RISKS"`
	ERQK_RISKV     string `json:"ERQK_RISKV"`
	HAIL_AFREQ     string `json:"HAIL_AFREQ"`
	HAIL_ALRA      string `json:"HAIL_ALRA"`
	HAIL_ALRB      string `json:"HAIL_ALRB"`
	HAIL_ALRP      string `json:"HAIL_ALRP"`
	HAIL_ALR_NPCTL string `json:"HAIL_ALR_NPCTL"`
	HAIL_EALA      string `json:"HAIL_EALA"`
	HAIL_EALB      string `json:"HAIL_EALB"`
	HAIL_EALP      string `json:"HAIL_EALP"`
	HAIL_EALPE     string `json:"HAIL_EALPE"`
	HAIL_EALR      string `json:"HAIL_EALR"`
	HAIL_EALS      string `json:"HAIL_EALS"`
	HAIL_EALT      string `json:"HAIL_EALT"`
	HAIL_EVNTS     string `json:"HAIL_EVNTS"`
	HAIL_EXPA      string `json:"HAIL_EXPA"`
	HAIL_EXPB      string `json:"HAIL_EXPB"`
	HAIL_EXPP      string `json:"HAIL_EXPP"`
	HAIL_EXPPE     string `json:"HAIL_EXPPE"`
	HAIL_EXPT      string `json:"HAIL_EXPT"`
	HAIL_EXP_AREA  string `json:"HAIL_EXP_AREA"`
	HAIL_HLRA      string `json:"HAIL_HLRA"`
	HAIL_HLRB      string `json:"HAIL_HLRB"`
	HAIL_HLRP      string `json:"HAIL_HLRP"`
	HAIL_HLRR      string `json:"HAIL_HLRR"`
	HAIL_RISKR     string `json:"HAIL_RISKR"`
	HAIL_RISKS     string `json:"HAIL_RISKS"`
	HAIL_RISKV     string `json:"HAIL_RISKV"`
	HRCN_AFREQ     string `json:"HRCN_AFREQ"`
	HRCN_ALRA      string `json:"HRCN_ALRA"`
	HRCN_ALRB      string `json:"HRCN_ALRB"`
	HRCN_ALRP      string `json:"HRCN_ALRP"`
	HRCN_ALR_NPCTL string `json:"HRCN_ALR_NPCTL"`
	HRCN_EALA      string `json:"HRCN_EALA"`
	HRCN_EALB      string `json:"HRCN_EALB"`
	HRCN_EALP      string `json:"HRCN_EALP"`
	HRCN_EALPE     string `json:"HRCN_EALPE"`
	HRCN_EALR      string `json:"HRCN_EALR"`
	HRCN_EALS      string `json:"HRCN_EALS"`
	HRCN_EALT      string `json:"HRCN_EALT"`
	HRCN_EVNTS     string `json:"HRCN_EVNTS"`
	HRCN_EXPA      string `json:"HRCN_EXPA"`
	HRCN_EXPB      string `json:"HRCN_EXPB"`
	HRCN_EXPP      string `json:"HRCN_EXPP"`
	HRCN_EXPPE     string `json:"HRCN_EXPPE"`
	HRCN_EXPT      string `json:"HRCN_EXPT"`
	HRCN_EXP_AREA  string `json:"HRCN_EXP_AREA"`
	HRCN_HLRA      string `json:"HRCN_HLRA"`
	HRCN_HLRB      string `json:"HRCN_HLRB"`
	HRCN_HLRP      string `json:"HRCN_HLRP"`
	HRCN_HLRR      string `json:"HRCN_HLRR"`
	HRCN_RISKR     string `json:"HRCN_RISKR"`
	HRCN_RISKS     string `json:"HRCN_RISKS"`
	HRCN_RISKV     string `json:"HRCN_RISKV"`
	HWAV_AFREQ     string `json:"HWAV_AFREQ"`
	HWAV_ALRA      string `json:"HWAV_ALRA"`
	HWAV_ALRB      string `json:"HWAV_ALRB"`
	HWAV_ALRP      string `json:"HWAV_ALRP"`
	HWAV_ALR_NPCTL string `json:"HWAV_ALR_NPCTL"`
	HWAV_EALA      string `json:"HWAV_EALA"`
	HWAV_EALB      string `json:"HWAV_EALB"`
	HWAV_EALP      string `json:"HWAV_EALP"`
	HWAV_EALPE     string `json:"HWAV_EALPE"`
	HWAV_EALR      string `json:"HWAV_EALR"`
	HWAV_EALS      string `json:"HWAV_EALS"`
	HWAV_EALT      string `json:"HWAV_EALT"`
	HWAV_EVNTS     string `json:"HWAV_EVNTS"`
	HWAV_EXPA      string `json:"HWAV_EXPA"`
	HWAV_EXPB      string `json:"HWAV_EXPB"`
	HWAV_EXPP      string `json:"HWAV_EXPP"`
	HWAV_EXPPE     string `json:"HWAV_EXPPE"`
	HWAV_EXPT      string `json:"HWAV_EXPT"`
	HWAV_EXP_AREA  string `json:"HWAV_EXP_AREA"`
	HWAV_HLRA      string `json:"HWAV_HLRA"`
	HWAV_HLRB      string `json:"HWAV_HLRB"`
	HWAV_HLRP      string `json:"HWAV_HLRP"`
	HWAV_HLRR      string `json:"HWAV_HLRR"`
	HWAV_RISKR     string `json:"HWAV_RISKR"`
	HWAV_RISKS     string `json:"HWAV_RISKS"`
	HWAV_RISKV     string `json:"HWAV_RISKV"`
	ISTM_AFREQ     string `json:"ISTM_AFREQ"`
	ISTM_ALRB      string `json:"ISTM_ALRB"`
	ISTM_ALRP      string `json:"ISTM_ALRP"`
	ISTM_ALR_NPCTL string `json:"ISTM_ALR_NPCTL"`
	ISTM_EALB      string `json:"ISTM_EALB"`
	ISTM_EALP      string `json:"ISTM_EALP"`
	ISTM_EALPE     string `json:"ISTM_EALPE"`
	ISTM_EALR      string `json:"ISTM_EALR"`
	ISTM_EALS      string `json:"ISTM_EALS"`
	ISTM_EALT      string `json:"ISTM_EALT"`
	ISTM_EVNTS     string `json:"ISTM_EVNTS"`
	ISTM_EXPB      string `json:"ISTM_EXPB"`
	ISTM_EXPP      string `json:"ISTM_EXPP"`
	ISTM_EXPPE     string `json:"ISTM_EXPPE"`
	ISTM_EXPT      string `json:"ISTM_EXPT"`
	ISTM_EXP_AREA  string `json:"ISTM_EXP_AREA"`
	ISTM_HLRB      string `json:"ISTM_HLRB"`
	ISTM_HLRP      string `json:"ISTM_HLRP"`
	ISTM_HLRR      string `json:"ISTM_HLRR"`
	ISTM_RISKR     string `json:"ISTM_RISKR"`
	ISTM_RISKS     string `json:"ISTM_RISKS"`
	ISTM_RISKV     string `json:"ISTM_RISKV"`
	LNDS_AFREQ     string `json:"LNDS_AFREQ"`
	LNDS_ALRB      string `json:"LNDS_ALRB"`
	LNDS_ALRP      string `json:"LNDS_ALRP"`
	LNDS_ALR_NPCTL string `json:"LNDS_ALR_NPCTL"`
	LNDS_EALB      string `json:"LNDS_EALB"`
	LNDS_EALP      string `json:"LNDS_EALP"`
	LNDS_EALPE     string `json:"LNDS_EALPE"`
	LNDS_EALR      string `json:"LNDS_EALR"`
	LNDS_EALS      string `json:"LNDS_EALS"`
	LNDS_EALT      string `json:"LNDS_EALT"`
	LNDS_EVNTS     string `json:"LNDS_EVNTS"`
	LNDS_EXPB      string `json:"LNDS_EXPB"`
	LNDS_EXPP      string `json:"LNDS_EXPP"`
	LNDS_EXPPE     string `json:"LNDS_EXPPE"`
	LNDS_EXPT      string `json:"LNDS_EXPT"`
	LNDS_EXP_AREA  string `json:"LNDS_EXP_AREA"`
	LNDS_HLRB      string `json:"LNDS_HLRB"`
	LNDS_HLRP      string `json:"LNDS_HLRP"`
	LNDS_HLRR      string `json:"LNDS_HLRR"`
	LNDS_RISKR     string `json:"LNDS_RISKR"`
	LNDS_RISKS     string `json:"LNDS_RISKS"`
	LNDS_RISKV     string `json:"LNDS_RISKV"`
	LTNG_AFREQ     string `json:"LTNG_AFREQ"`
	LTNG_ALRB      string `json:"LTNG_ALRB"`
	LTNG_ALRP      string `json:"LTNG_ALRP"`
	LTNG_ALR_NPCTL string `json:"LTNG_ALR_NPCTL"`
	LTNG_EALB      string `json:"LTNG_EALB"`
	LTNG_EALP      string `json:"LTNG_EALP"`
	LTNG_EALPE     string `json:"LTNG_EALPE"`
	LTNG_EALR      string `json:"LTNG_EALR"`
	LTNG_EALS      string `json:"LTNG_EALS"`
	LTNG_EALT      string `json:"LTNG_EALT"`
	LTNG_EVNTS     string `json:"LTNG_EVNTS"`
	LTNG_EXPB      string `json:"LTNG_EXPB"`
	LTNG_EXPP      string `json:"LTNG_EXPP"`
	LTNG_EXPPE     string `json:"LTNG_EXPPE"`
	LTNG_EXPT      string `json:"LTNG_EXPT"`
	LTNG_EXP_AREA  string `json:"LTNG_EXP_AREA"`
	LTNG_HLRB      string `json:"LTNG_HLRB"`
	LTNG_HLRP      string `json:"LTNG_HLRP"`
	LTNG_HLRR      string `json:"LTNG_HLRR"`
	LTNG_RISKR     string `json:"LTNG_RISKR"`
	LTNG_RISKS     string `json:"LTNG_RISKS"`
	LTNG_RISKV     string `json:"LTNG_RISKV"`
	NRI_VER        string `json:"NRI_VER"`
	POPULATION     string `json:"POPULATION"`
	RESL_RATNG     string `json:"RESL_RATNG"`
	RESL_SCORE     string `json:"RESL_SCORE"`
	RESL_SPCTL     string `json:"RESL_SPCTL"`
	RESL_VALUE     string `json:"RESL_VALUE"`
	RFLD_AFREQ     string `json:"RFLD_AFREQ"`
	RFLD_ALRA      string `json:"RFLD_ALRA"`
	RFLD_ALRB      string `json:"RFLD_ALRB"`
	RFLD_ALRP      string `json:"RFLD_ALRP"`
	RFLD_ALR_NPCTL string `json:"RFLD_ALR_NPCTL"`
	RFLD_EALA      string `json:"RFLD_EALA"`
	RFLD_EALB      string `json:"RFLD_EALB"`
	RFLD_EALP      string `json:"RFLD_EALP"`
	RFLD_EALPE     string `json:"RFLD_EALPE"`
	RFLD_EALR      string `json:"RFLD_EALR"`
	RFLD_EALS      string `json:"RFLD_EALS"`
	RFLD_EALT      string `json:"RFLD_EALT"`
	RFLD_EVNTS     string `json:"RFLD_EVNTS"`
	RFLD_EXPA      string `json:"RFLD_EXPA"`
	RFLD_EXPB      string `json:"RFLD_EXPB"`
	RFLD_EXPP      string `json:"RFLD_EXPP"`
	RFLD_EXPPE     string `json:"RFLD_EXPPE"`
	RFLD_EXPT      string `json:"RFLD_EXPT"`
	RFLD_EXP_AREA  string `json:"RFLD_EXP_AREA"`
	RFLD_HLRA      string `json:"RFLD_HLRA"`
	RFLD_HLRB      string `json:"RFLD_HLRB"`
	RFLD_HLRP      string `json:"RFLD_HLRP"`
	RFLD_HLRR      string `json:"RFLD_HLRR"`
	RFLD_RISKR     string `json:"RFLD_RISKR"`
	RFLD_RISKS     string `json:"RFLD_RISKS"`
	RFLD_RISKV     string `json:"RFLD_RISKV"`
	RISK_RATNG     string `json:"RISK_RATNG"`
	RISK_SCORE     string `json:"RISK_SCORE"`
	RISK_SPCTL     string `json:"RISK_SPCTL"`
	RISK_VALUE     string `json:"RISK_VALUE"`
	SOVI_RATNG     string `json:"SOVI_RATNG"`
	SOVI_SCORE     string `json:"SOVI_SCORE"`
	SOVI_SPCTL     string `json:"SOVI_SPCTL"`
	STATE          string `json:"STATE"`
	STATEABBRV     string `json:"STATEABBRV"`
	STATEFIPS      string `json:"STATEFIPS"`
	STCOFIPS       string `json:"STCOFIPS"`
	SWND_AFREQ     string `json:"SWND_AFREQ"`
	SWND_ALRA      string `json:"SWND_ALRA"`
	SWND_ALRB      string `json:"SWND_ALRB"`
	SWND_ALRP      string `json:"SWND_ALRP"`
	SWND_ALR_NPCTL string `json:"SWND_ALR_NPCTL"`
	SWND_EALA      string `json:"SWND_EALA"`
	SWND_EALB      string `json:"SWND_EALB"`
	SWND_EALP      string `json:"SWND_EALP"`
	SWND_EALPE     string `json:"SWND_EALPE"`
	SWND_EALR      string `json:"SWND_EALR"`
	SWND_EALS      string `json:"SWND_EALS"`
	SWND_EALT      string `json:"SWND_EALT"`
	SWND_EVNTS     string `json:"SWND_EVNTS"`
	SWND_EXPA      string `json:"SWND_EXPA"`
	SWND_EXPB      string `json:"SWND_EXPB"`
	SWND_EXPP      string `json:"SWND_EXPP"`
	SWND_EXPPE     string `json:"SWND_EXPPE"`
	SWND_EXPT      string `json:"SWND_EXPT"`
	SWND_EXP_AREA  string `json:"SWND_EXP_AREA"`
	SWND_HLRA      string `json:"SWND_HLRA"`
	SWND_HLRB      string `json:"SWND_HLRB"`
	SWND_HLRP      string `json:"SWND_HLRP"`
	SWND_HLRR      string `json:"SWND_HLRR"`
	SWND_RISKR     string `json:"SWND_RISKR"`
	SWND_RISKS     string `json:"SWND_RISKS"`
	SWND_RISKV     string `json:"SWND_RISKV"`
	TRACT          string `json:"TRACT"`
	TRACTFIPS      string `json:"TRACTFIPS"`
	TRND_AFREQ     string `json:"TRND_AFREQ"`
	TRND_ALRA      string `json:"TRND_ALRA"`
	TRND_ALRB      string `json:"TRND_ALRB"`
	TRND_ALRP      string `json:"TRND_ALRP"`
	TRND_ALR_NPCTL string `json:"TRND_ALR_NPCTL"`
	TRND_EALA      string `json:"TRND_EALA"`
	TRND_EALB      string `json:"TRND_EALB"`
	TRND_EALP      string `json:"TRND_EALP"`
	TRND_EALPE     string `json:"TRND_EALPE"`
	TRND_EALR      string `json:"TRND_EALR"`
	TRND_EALS      string `json:"TRND_EALS"`
	TRND_EALT      string `json:"TRND_EALT"`
	TRND_EVNTS     string `json:"TRND_EVNTS"`
	TRND_EXPA      string `json:"TRND_EXPA"`
	TRND_EXPB      string `json:"TRND_EXPB"`
	TRND_EXPP      string `json:"TRND_EXPP"`
	TRND_EXPPE     string `json:"TRND_EXPPE"`
	TRND_EXPT      string `json:"TRND_EXPT"`
	TRND_EXP_AREA  string `json:"TRND_EXP_AREA"`
	TRND_HLRA      string `json:"TRND_HLRA"`
	TRND_HLRB      string `json:"TRND_HLRB"`
	TRND_HLRP      string `json:"TRND_HLRP"`
	TRND_HLRR      string `json:"TRND_HLRR"`
	TRND_RISKR     string `json:"TRND_RISKR"`
	TRND_RISKS     string `json:"TRND_RISKS"`
	TRND_RISKV     string `json:"TRND_RISKV"`
	TSUN_AFREQ     string `json:"TSUN_AFREQ"`
	TSUN_ALRB      string `json:"TSUN_ALRB"`
	TSUN_ALRP      string `json:"TSUN_ALRP"`
	TSUN_ALR_NPCTL string `json:"TSUN_ALR_NPCTL"`
	TSUN_EALB      string `json:"TSUN_EALB"`
	TSUN_EALP      string `json:"TSUN_EALP"`
	TSUN_EALPE     string `json:"TSUN_EALPE"`
	TSUN_EALR      string `json:"TSUN_EALR"`
	TSUN_EALS      string `json:"TSUN_EALS"`
	TSUN_EALT      string `json:"TSUN_EALT"`
	TSUN_EVNTS     string `json:"TSUN_EVNTS"`
	TSUN_EXPB      string `json:"TSUN_EXPB"`
	TSUN_EXPP      string `json:"TSUN_EXPP"`
	TSUN_EXPPE     string `json:"TSUN_EXPPE"`
	TSUN_EXPT      string `json:"TSUN_EXPT"`
	TSUN_EXP_AREA  string `json:"TSUN_EXP_AREA"`
	TSUN_HLRB      string `json:"TSUN_HLRB"`
	TSUN_HLRP      string `json:"TSUN_HLRP"`
	TSUN_HLRR      string `json:"TSUN_HLRR"`
	TSUN_RISKR     string `json:"TSUN_RISKR"`
	TSUN_RISKS     string `json:"TSUN_RISKS"`
	TSUN_RISKV     string `json:"TSUN_RISKV"`
	VLCN_AFREQ     string `json:"VLCN_AFREQ"`
	VLCN_ALRB      string `json:"VLCN_ALRB"`
	VLCN_ALRP      string `json:"VLCN_ALRP"`
	VLCN_ALR_NPCTL string `json:"VLCN_ALR_NPCTL"`
	VLCN_EALB      string `json:"VLCN_EALB"`
	VLCN_EALP      string `json:"VLCN_EALP"`
	VLCN_EALPE     string `json:"VLCN_EALPE"`
	VLCN_EALR      string `json:"VLCN_EALR"`
	VLCN_EALS      string `json:"VLCN_EALS"`
	VLCN_EALT      string `json:"VLCN_EALT"`
	VLCN_EVNTS     string `json:"VLCN_EVNTS"`
	VLCN_EXPB      string `json:"VLCN_EXPB"`
	VLCN_EXPP      string `json:"VLCN_EXPP"`
	VLCN_EXPPE     string `json:"VLCN_EXPPE"`
	VLCN_EXPT      string `json:"VLCN_EXPT"`
	VLCN_EXP_AREA  string `json:"VLCN_EXP_AREA"`
	VLCN_HLRB      string `json:"VLCN_HLRB"`
	VLCN_HLRP      string `json:"VLCN_HLRP"`
	VLCN_HLRR      string `json:"VLCN_HLRR"`
	VLCN_RISKR     string `json:"VLCN_RISKR"`
	VLCN_RISKS     string `json:"VLCN_RISKS"`
	VLCN_RISKV     string `json:"VLCN_RISKV"`
	WFIR_AFREQ     string `json:"WFIR_AFREQ"`
	WFIR_ALRA      string `json:"WFIR_ALRA"`
	WFIR_ALRB      string `json:"WFIR_ALRB"`
	WFIR_ALRP      string `json:"WFIR_ALRP"`
	WFIR_ALR_NPCTL string `json:"WFIR_ALR_NPCTL"`
	WFIR_EALA      string `json:"WFIR_EALA"`
	WFIR_EALB      string `json:"WFIR_EALB"`
	WFIR_EALP      string `json:"WFIR_EALP"`
	WFIR_EALPE     string `json:"WFIR_EALPE"`
	WFIR_EALR      string `json:"WFIR_EALR"`
	WFIR_EALS      string `json:"WFIR_EALS"`
	WFIR_EALT      string `json:"WFIR_EALT"`
	WFIR_EVNTS     string `json:"WFIR_EVNTS"`
	WFIR_EXPA      string `json:"WFIR_EXPA"`
	WFIR_EXPB      string `json:"WFIR_EXPB"`
	WFIR_EXPP      string `json:"WFIR_EXPP"`
	WFIR_EXPPE     string `json:"WFIR_EXPPE"`
	WFIR_EXPT      string `json:"WFIR_EXPT"`
	WFIR_EXP_AREA  string `json:"WFIR_EXP_AREA"`
	WFIR_HLRA      string `json:"WFIR_HLRA"`
	WFIR_HLRB      string `json:"WFIR_HLRB"`
	WFIR_HLRP      string `json:"WFIR_HLRP"`
	WFIR_HLRR      string `json:"WFIR_HLRR"`
	WFIR_RISKR     string `json:"WFIR_RISKR"`
	WFIR_RISKS     string `json:"WFIR_RISKS"`
	WFIR_RISKV     string `json:"WFIR_RISKV"`
	WNTW_AFREQ     string `json:"WNTW_AFREQ"`
	WNTW_ALRA      string `json:"WNTW_ALRA"`
	WNTW_ALRB      string `json:"WNTW_ALRB"`
	WNTW_ALRP      string `json:"WNTW_ALRP"`
	WNTW_ALR_NPCTL string `json:"WNTW_ALR_NPCTL"`
	WNTW_EALA      string `json:"WNTW_EALA"`
	WNTW_EALB      string `json:"WNTW_EALB"`
	WNTW_EALP      string `json:"WNTW_EALP"`
	WNTW_EALPE     string `json:"WNTW_EALPE"`
	WNTW_EALR      string `json:"WNTW_EALR"`
	WNTW_EALS      string `json:"WNTW_EALS"`
	WNTW_EALT      string `json:"WNTW_EALT"`
	WNTW_EVNTS     string `json:"WNTW_EVNTS"`
	WNTW_EXPA      string `json:"WNTW_EXPA"`
	WNTW_EXPB      string `json:"WNTW_EXPB"`
	WNTW_EXPP      string `json:"WNTW_EXPP"`
	WNTW_EXPPE     string `json:"WNTW_EXPPE"`
	WNTW_EXPT      string `json:"WNTW_EXPT"`
	WNTW_EXP_AREA  string `json:"WNTW_EXP_AREA"`
	WNTW_HLRA      string `json:"WNTW_HLRA"`
	WNTW_HLRB      string `json:"WNTW_HLRB"`
	WNTW_HLRP      string `json:"WNTW_HLRP"`
	WNTW_HLRR      string `json:"WNTW_HLRR"`
	WNTW_RISKR     string `json:"WNTW_RISKR"`
	WNTW_RISKS     string `json:"WNTW_RISKS"`
	WNTW_RISKV     string `json:"WNTW_RISKV"`
}
